Vagrant.configure("2") do |config|
  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
  SHELL
  # control plan
  config.vm.define :control do |control|
    control.vm.box = "ubuntu/bionic64"
    control.vm.box_version = "20230607.0.5"
    control.vm.provider "virtualbox"
    control.vm.network "private_network", ip: "192.168.56.30"
  end
  # worker 1
  config.vm.define :worker1 do |worker1|
    worker1.vm.box = "ubuntu/bionic64"
    worker1.vm.box_version = "20230607.0.5"
    worker1.vm.provider "virtualbox"
    worker1.vm.network "private_network", ip: "192.168.56.31"
  end
  # worker 2
  config.vm.define :worker2 do |worker2|
    worker2.vm.box = "ubuntu/bionic64"
    worker2.vm.box_version = "20230607.0.5"
    worker2.vm.provider "virtualbox"
    worker2.vm.network "private_network", ip: "192.168.56.32"
  end
end
