Vagrant.configure("2") do |config|
  # DHCP Server
  config.vm.define :server do |server|
    server.vm.box = "generic/debian12"
    server.vm.box_version = "4.3.12"
    server.vm.hostname = "server"

    server.vm.provider "virtualbox" do |virtualbox|
      virtualbox.cpus = 2
      virtualbox.memory = 2048
    end

    server.vm.network :public_network, bridge: "wlp1s0", ip: "192.168.100.50"
    server.vm.network :private_network, ip: "10.200.0.1", netmask: "255.0.0.0"
    server.ssh.insert_key = false
    server.ssh.private_key_path = ['~/.vagrant.d/insecure_private_key', '~/.ssh/id_rsa']
    server.vm.provision :file, source: "~/.vagrant.d/insecure_private_key", destination: "~/.ssh/id_rsa"
    server.vm.provision :file, source: "~/vangrant/debian/interfaces", destination: "/tmp/interfaces"
    server.vm.provision :shell, inline: <<-SHELL
      sudo apt-get update --yes
      sudo apt-get install isc-dhcp-server --yes 2> /dev/null
      sudo cp  /tmp/interfaces /etc/network/interfaces
    SHELL

    
  end
  # for each machine
  (1..2).each do |machine|
    config.vm.define "node#{machine}" do |node|
      node.vm.box = "generic/debian12"
      node.vm.box_version = "4.3.12"
      node.vm.hostname = "node#{machine}"
      node.vm.provider "virtualbox" do |virtualbox|
        virtualbox.cpus = 1
        virtualbox.memory = 2048
      end
      config.vm.network :private_network, :ip =>'0.0.0.0', :auto_network => true 
      node.ssh.insert_key = false
      node.ssh.private_key_path = ['~/.vagrant.d/insecure_private_key', '~/.ssh/id_rsa']
      node.vm.provision :file, source: "~/.vagrant.d/insecure_private_key", destination: "~/.ssh/id_rsa"
    end
  end
end