Vagrant.configure("2") do |config|
  # DHCP Server
  config.vm.define :server do |server|
    server.vm.box = "generic/debian12"
    server.vm.box_version = "4.3.12"
    server.vm.hostname = "server"

    server.vm.provider "virtualbox" do |virtualbox|
      virtualbox.cpus = 2
      virtualbox.memory = 2048
    end

    server.vm.network :public_network, bridge: "wlp1s0", ip: "192.168.100.50"
    server.vm.network :private_network, ip: "192.168.56.30"
    server.ssh.insert_key = false
    server.ssh.private_key_path = ['~/.vagrant.d/insecure_private_key', '~/.ssh/id_rsa']
    server.vm.provision :file, source: "~/.vagrant.d/insecure_private_key", destination: "~/.ssh/id_rsa"
  end
  # for each machine
  (1..2).each do |machine|
    config.vm.define "node#{machine}" do |node|
      node.vm.box = "generic/debian12"
      node.vm.box_version = "4.3.12"
      node.vm.hostname = "node#{machine}"
      node.vm.provider "virtualbox" do |virtualbox|
        virtualbox.cpus = 1
        virtualbox.memory = 2048
      end
      node.vm.network :private_network, ip: "192.168.56.3#{machine}"
      node.ssh.insert_key = false
      node.ssh.private_key_path = ['~/.vagrant.d/insecure_private_key', '~/.ssh/id_rsa']
      node.vm.provision :file, source: "~/.vagrant.d/insecure_private_key", destination: "~/.ssh/id_rsa"
    end
  end
end