Vagrant.configure("2") do |config|
  # ubuntu plane
  config.vm.define :ubuntu do |ubuntu|
    ubuntu.vm.box = "bento/ubuntu-22.04"
    ubuntu.vm.box_version = "202502.21.0"
    ubuntu.vm.hostname = "ubuntu"
    ubuntu.vm.provider "virtualbox" do |virtualbox|
      virtualbox.cpus = 2
      virtualbox.memory = 2048
    end
    ubuntu.vm.network "public_network", bridge: "wlp1s0", ip: "192.168.100.30"
    ubuntu.ssh.insert_key = false
    ubuntu.ssh.private_key_path = ['~/.vagrant.d/insecure_private_key', '~/.ssh/id_rsa']
    ubuntu.vm.provision :file, source: "~/.vagrant.d/insecure_private_key", destination: "~/.ssh/id_rsa"
  end
end